name: another_eden_tracker
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  build_runner: ^2.4.7 # use 'dart run build_runner build --delete-conflicting-outputs' to generate
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_launcher_icons: ^0.13.1
  go_router: ^13.0.0
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  isar_generator: ^3.1.0+1
  path_provider: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

flutter_launcher_icons:
  image_path: "assets/images/icon.png"
  android: true # can specify file name here e.g. "ic_launcher"
  min_sdk_android: 21 # android min sdk min:16, default 21
  # use 'dart run flutter_launcher_icons' to generate icon
